namespace WinUI3Utilities.Internal.PlatformInvoke;

internal enum SystemMetric
{
    CxScreen = 0,
    CyScreen = 1,
    CxvScroll = 2,
    CyhScroll = 3,
    CyCaption = 4,
    CxBorder = 5,
    CyBorder = 6,
    CxDlgFrame = 7,
    CyDlgFrame = 8,
    CyvThumb = 9,
    CxhThumb = 10,
    CxIcon = 11,
    CyIcon = 12,
    CxCursor = 13,
    CyCursor = 14,
    CyMenu = 15,
    CxFullscreen = 16,
    CyFullscreen = 17,
    CyKanjiWindow = 18,
    MousePresent = 19,
    CyvScroll = 20,
    CxhScroll = 21,
    Debug = 22,
    SwapButton = 23,
    Reserved1 = 24,
    Reserved2 = 25,
    Reserved3 = 26,
    Reserved4 = 27,
    CxMin = 28,
    CyMin = 29,
    CxSize = 30,
    CySize = 31,
    CxFrame = 32,
    CyFrame = 33,
    CxMinTrack = 34,
    CyMinTrack = 35,
    CxDoubleClk = 36,
    CyDoubleClk = 37,
    CxIconSpacing = 38,
    CyIconSpacing = 39,
    MenuDropAlignment = 40,
    PenWindows = 41,
    DbcsEnabled = 42,
    CMouseButtons = 43,

    CxFixedFrame = CxDlgFrame /* ;win40 name change */,
    CyFixedFrame = CyDlgFrame /* ;win40 name change */,
    CxSizeFrame = CxFrame /* ;win40 name change */,
    CySizeFrame = CyFrame /* ;win40 name change */,

    Secure = 44,
    CxEdge = 45,
    CyEdge = 46,
    CxMinSpacing = 47,
    CyMinSpacing = 48,
    CxSmIcon = 49,
    CySmIcon = 50,
    CySmCaption = 51,
    CxSmSize = 52,
    CySmSize = 53,
    CxMenuSize = 54,
    CyMenuSize = 55,
    Arrange = 56,
    CxMinimized = 57,
    CyMinimized = 58,
    CxMaxTrack = 59,
    CyMaxTrack = 60,
    CxMaximized = 61,
    CyMaximized = 62,
    Network = 63,
    CleanBoot = 67,
    CxDrag = 68,
    CyDrag = 69,
    ShowSounds = 70,
    CxMenuCheck = 71 /* Use instead of GetMenuCheckMarkDimensions()! */,
    CyMenuCheck = 72,
    SlowMachine = 73,
    MideastEnabled = 74,

    MousewheelPresent = 75,
    XVirtualScreen = 76,
    YVirtualScreen = 77,
    CxVirtualScreen = 78,
    CyVirtualScreen = 79,
    CMonitors = 80,
    SameDisplayFormat = 81,
    ImmEnabled = 82,
    CxFocusBorder = 83,
    CyFocusBorder = 84,

    TableTpc = 86,
    MediaCenter = 87,
    Starter = 88,
    ServErr2 = 89,

    MouseHorizontalWheelPresent = 91,
    CxPaddedBorder = 92,

    Digitizer = 94,
    MaximumTouches = 95,

    CMetrics = 97,

    RemoteSession = 0x1000,

    ShuttingDown = 0x2000,

    RemoteControl = 0x2001,

    CaretBlinkingEnabled = 0x2002,

    ConvertiblesLateMode = 0x2003,
    SystemDocked = 0x2004
}
