using System;

namespace WinUI3Utilities.Attributes;

/// <summary>
/// Specify which properties will not be generated by <see cref="SettingsViewModelAttribute{T}"/> (only valid on property)
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class SettingsViewModelExclusionAttribute : Attribute
{

}
